SELECT CRON.ID_CRONOGRAMA AS[ID_CRONOGRAMA], 
		CRON.DT_EXEC_PLAN AS[DATA_EXECUCAO_PLANEJADO], 
		CRON.ESFORCO_PLAN AS[ESFORCO_PLANEJADO], 
		TIP_EVE.EVENTO AS[EVENTO], 
		CLI.CLIENTE AS[CLIENTE], 
		TB5.SETOR AS[INTRAG], 
		FUN.SIGLA_SAC AS[SIGLA_SAC], 
		FUN.SIGLA_FY AS[SIGLA_FY], 
		FUN.CNPJ_CPF AS[CNPJ_CPF], 
		DESC_EVE.DTDEMANDA AS[DATA_DEMANDA], 
		FUN.RAZAO_SOCIAL AS[RAZAO_SOCIAL], 
		CRON.RESPONSAVEL AS[RESPONSAVEL], 
		EVE.SEQ_EVENTO AS[ID_DEMANDA], 
		CRON.ATIVIDADE AS[ATIVIDADE], 
		CRON.AVALIACAO AS[AVALIACAO], 
		CRON.STATUS AS[STATUS] 
FROM CRONOGRAMA_TB CRON, 
	TIPO_EVENTO_TB TIP_EVE, 
	CLIENTE_TB CLI, 
	EVENTO_TB EVE, 
	SETOR_TB TB5, 
	REL_EVENTO_SETOR_TB REL_EVE, 
	ATIVIDADE_TB ATIV, 
	DESCRICAO_EVENTO_TB DESC_EVE, 
	FUNDO_TB FUN 
WHERE CRON.ID_TP_EVENTO 	= ATIV.ID_TP_EVENTO 	AND 
	ATIV.ID_TP_EVENTO 		= TIP_EVE.ID_TP_EVENTO 	AND 
	TIP_EVE.ID_TP_EVENTO 	= DESC_EVE.ID_TP_EVENTO AND 
	DESC_EVE.SEQ_EVENTO 	= CRON.SEQ_EVENTO 		AND 
	EVE.SEQ_EVENTO 			= CRON.SEQ_EVENTO 		AND 
	EVE.ID_CLIENTE 			= CLI.ID_CLIENTE 		AND 
	EVE.ID_FUNDO 			= FUN.ID_FUNDO 			AND 
	TB5.ID_SETOR 			= REL_EVE.ID_SETOR 		AND 
	REL_EVE.SEQ_EVENTO 		= EVE.SEQ_EVENTO 
GROUP BY CRON.ID_CRONOGRAMA, CRON.DT_EXEC_PLAN, CRON.ESFORCO_PLAN, TIP_EVE.EVENTO, 
		CLI.CLIENTE, TB5.SETOR, FUN.SIGLA_SAC, FUN.SIGLA_FY, FUN.CNPJ_CPF, 
		DESC_EVE.DTDEMANDA, FUN.RAZAO_SOCIAL, CRON.RESPONSAVEL, EVE.SEQ_EVENTO, 
		CRON.ATIVIDADE, CRON.AVALIACAO, CRON.STATUS 